version: 3
dependencies:
- type: git
  settings:
    remotes:
      https://github.com/hyperion-project/hyperion.ng.git:
        replace_in_files:
        - filename: addon-hyperion-ng/config.json
          pattern: '"version": "(\S+)"'
          semver: false
