sudo: required
services:
  - docker
env:
  - ADDON="addon-hyperion-ng"
script:
  - docker run --rm --name hassio-builder --privileged \
    -v /var/run/docker.sock:/var/run/docker.sock:ro \
    -v ~/.docker:/root/.docker homeassistant/amd64-builder \
    -v $(pwd)/${ADDON}:/data \
    -t data \
    --no-cache \
    --docker-user ${DOCKER_USER} \
    --docker-password ${DOCKER_PASSWORD} \
    --all
