language: minimal
arch: amd64
os: linux
dist: focal
services:
  - docker
env:
  - ADDON="addon-hyperion-ng" ARCH="amd64"
  - ADDON="addon-hyperion-ng" ARCH="armhf"
  - ADDON="addon-hyperion-ng" ARCH="armv7"
  - ADDON="addon-hyperion-ng" ARCH="aarch64"
  - ADDON="addon-hyperion-ng" ARCH="i386"
script: >
  docker run --rm --privileged
  -v /var/run/docker.sock:/var/run/docker.sock:ro
  -v ~/.docker:/root/.docker
  -v ${TRAVIS_BUILD_DIR}/${ADDON}:/data
  homeassistant/amd64-builder
  --target /data
  --no-cache
  --docker-user "${DOCKER_USER}"
  --docker-password "${DOCKER_PASSWORD}"
  --${ARCH}

